create table interests (
  id bigint generated by default as identity primary key,
  name varchar(80) not null unique,
  category varchar(255) not null
);
insert into interests (name, category) values ('Музыка', 'Творчество');

